### ISSUE TITLE
Number mangling

### ISSUE THREAD

**Issue by hermanius** [nakagami/efirebirdsql#10]
Hi,

I have a strange problem with efirebirdsql 0.8.2 - FirebirdSQL 2.5
When I do a query on an integer field with a value between 128 and 160, the value is not read correctly through a fetchall.
e.g:
SELECT * FROM VWOPARAMS WHERE vwa_id = 159
result = (look at vwa_id)
[
  %{
    "vwa_aanvangsdatum" => {{1975, 4, 1}, {0, 0, 0, 0}},
    "vwa_code" => "DEELCERTIFICAAT",
    "vwa_einddatum" => {{2999, 6, 30}, {0, 0, 0, 0}},
    "vwa_extra" => nil,
    "vwa_id" => 376,
    "vwa_omschrijving" => "Deelcertificaat",
    "vwa_recordtype" => "O",
    "vwa_type" => "VWST",
    "vwa_veranderddoor" => 0,
    "vwa_veranderdop" => {{2018, 5, 11}, {16, 4, 10, 0}}
  }
]

SELECT * FROM VWOPARAMS WHERE vwa_id = 160
result = (look again at vwa_id)
[
  %{
    "vwa_aanvangsdatum" => {{1975, 4, 1}, {0, 0, 0, 0}},
    "vwa_code" => "GEGRADUEERDE",
    "vwa_einddatum" => {{2999, 6, 30}, {0, 0, 0, 0}},
    "vwa_extra" => nil,
    "vwa_id" => 160,
    "vwa_omschrijving" => "Diploma gegradueerde",
    "vwa_recordtype" => "O",
    "vwa_type" => "VWST",
    "vwa_veranderddoor" => 0,
    "vwa_veranderdop" => {{2018, 5, 11}, {16, 4, 10, 0}}
  }
]

<img width="383" alt="image" src="https://user-images.githubusercontent.com/16594513/171154167-f31de5a1-0f1a-451d-9c76-1e1f2435ee8f.png">

This is happening also on other tables with the same kind of fields & queries, so it does not appear to be a problem isolated to just 1 table that maybe could be corrupt.
I hope you are able to help my out. Thank you in advance.

**Comment by nakagami** [comment]
I do not know.
The client library does not parse SQL statements, it just passes strings to Firebird, so I don't think that would happen.

Are the result values wrong?
Or is the value 376 and you can't limit it with WHERE?

If you could pull request the failed test case, we might be able to find out something.

**Comment by hermanius** [comment]
The SQL statement itself does return the right record (=record with vwa_id=159), so I think as you already mentioned,  the passing and interpretation of the SQL-statement by the database itself is correct. 
It's just the value of the returned vwa_id that is wrong. It should be 159, but returns the wrong value of 376.
When I try the same statement from Python and Java it returns the correct value, so it looks like it must be happening somewhere in the parsing of the results in the client. Is that possible? Can it have something to do with the fact the database uses a win1252 encoding (although vwa_id is an integer, and not a string)?

I don't really know how to create a pull request for a test, because I'm using efirebirdsql from Elixir, and not directly in Erlang,  and I'm not really an Erlang developer.
If it's not easy for you to reproduce the problem I can still try to create a test case, but it would be a big effort not knowing Erlang, so I'm hoping your deep knowledge of the library might give a pointer to where the issue might be.

**Comment by nakagami** [comment]
I see, so regardless of where, it returns 376 instead of 159 in the database?

Can you show me the create table statement for the VWOPARAMS table? I would like to know how you declare the type of VWA_ID

**Comment by hermanius** [comment]
Thank you so much for looking into this, and yes, 376 is always returned in stead of 159. This is from another table where I also select on vom_id=159, and again it returns the right record, with the wrong value for VOM_ID:
[
  %{
    "vom_begindatum" => {1975, 4, 1},
    "vom_code" => "00000159",
    "vom_einddatum" => {2999, 6, 30},
    "vom_geannuleerd" => "-",
    "vom_id" => 376,
    "vom_omschrijving" => "Begeleiding van het schoolgaande kind 1"
  }
]

Here is the build script for the VWO_PARAMS table, and I have also attached the script to create all the records currently in the table.

CREATE TABLE VWOPARAMS (
	VWA_VERANDERDDOOR INTEGER NOT NULL,
	VWA_VERANDERDOP TIMESTAMP NOT NULL,
	VWA_RECORDTYPE CHAR(1) DEFAULT 'U' NOT NULL,
	VWA_ID INTEGER NOT NULL,
	VWA_TYPE VARCHAR(5) NOT NULL,
	VWA_CODE VARCHAR(50) NOT NULL,
	VWA_OMSCHRIJVING VARCHAR(1000) NOT NULL,
	VWA_AANVANGSDATUM TIMESTAMP NOT NULL,
	VWA_EINDDATUM TIMESTAMP NOT NULL,
	VWA_EXTRA VARCHAR(50),
	CONSTRAINT PK_VWOPARAMS PRIMARY KEY (VWA_ID),
	CONSTRAINT U_VWPCODETYPE UNIQUE (VWA_CODE,VWA_TYPE)
);

[vwo_params.txt](https://github.com/nakagami/efirebirdsql/files/8805686/vwo_params.txt)

**Comment by nakagami** [comment]
Hmmm, I tried it here and it seems to be working properly.

```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1]

Eshell V10.6.4  (abort with ^G)
1> {ok, C} = efirebirdsql:connect("localhost", "sysdba", "masterkey", "/opt/data/issue10.fdb", []).
{ok,<0.80.0>}
2> ok = efirebirdsql:execute(C, <<"SELECT * FROM VWOPARAMS WHERE vwa_id = 159">>).
ok
3> {ok, Results} = efirebirdsql:fetchall(C).
{ok,[[{<<"VWA_VERANDERDDOOR">>,0},
      {<<"VWA_VERANDERDOP">>,{{2018,5,11},{16,4,10,0}}},
      {<<"VWA_RECORDTYPE">>,<<"O">>},
      {<<"VWA_ID">>,159},
      {<<"VWA_TYPE">>,<<"VWST">>},
      {<<"VWA_CODE">>,<<"DEELCERTIFICAAT">>},
      {<<"VWA_OMSCHRIJVING">>,<<"Deelcertificaat">>},
      {<<"VWA_AANVANGSDATUM">>,{{1975,4,1},{0,0,0,0}}},
      {<<"VWA_EINDDATUM">>,{{2999,6,30},{0,0,0,0}}},
      {<<"VWA_EXTRA">>,nil}]]}
4> 
```
I checked with Firebird 4.0, but I think it's the same with Firebird 2.5

**Comment by hermanius** [comment]
Oh, my God. So stupid of me.
The database is in WIN1252 encoding, and after every query I do a conversion to unicode before further processing (which I forgot about because it is hidden in a library).
The problem was that the conversion was done for every type of field, including integer fields, and apparently this caused problems for some ranges of integers. Now that I have fixed my code to only do the conversion on binary fields the problem is gone.

Thank you a thousand times.
I feel a bit ashamed to have taken up valuable time from you to chase this issue, which was a mistake on my end. Is there any way I can make up for it?

**Comment by nakagami** [comment]
No problem.
I am happy to report that you have used this library and that it works correctly!
