### ISSUE TITLE
con_byte4 error on large integers

### ISSUE THREAD

**Issue by hermanius** [nakagami/efirebirdsql#17]
I have a table defined as follows:
`CREATE TABLE VWOKLAS (
	VWK_ID INTEGER NOT NULL,
        .....`

Consider the following simple query: `SELECT FIRST 1 VWK_ID FROM VWOKLAS WHERE VWK_ID = ?`
When I run this query with VWK_ID param = 123, I get a normal result, no problem.
When I run the query however with a very large VWK_ID param like for example 123456789999999999
The process crashes with error message:
`
** (CaseClauseError) no case clause matching: 8
    (efirebirdsql 0.9.2) /elixir/cvodvd/deps/efirebirdsql/src/efirebirdsql_conv.erl:25: :efirebirdsql_conv.byte4/2
    (efirebirdsql 0.9.2) /elixir/cvodvd/deps/efirebirdsql/src/efirebirdsql_conv.erl:159: :efirebirdsql_conv.param_to_blr/2
    (efirebirdsql 0.9.2) /elixir/cvodvd/deps/efirebirdsql/src/efirebirdsql_conv.erl:233: :efirebirdsql_conv.params_to_blr/5
    (efirebirdsql 0.9.2) /elixir/cvodvd/deps/efirebirdsql/src/efirebirdsql_conv.erl:241: :efirebirdsql_conv.params_to_blr/3
    (efirebirdsql 0.9.2) /elixir/cvodvd/deps/efirebirdsql/src/efirebirdsql_op.erl:296: :efirebirdsql_op.op_execute/3
    (efirebirdsql 0.9.2) /elixir/cvodvd/deps/efirebirdsql/src/efirebirdsql_protocol.erl:204: :efirebirdsql_protocol.execute/4`

It seems efirebirdsql_con.byte4/2 only handles cases from 1 to 4, but apparently larger values are also possible.
Is there a way to handle these cases more elegantly without a crash?

**Comment by nakagami** [comment]
Fixes merged into master.
Can you check if it works correctly in master HEAD?

**Comment by hermanius** [comment]
Sorry for the late reaction, we had a few holidays here the last few days.

Yes, it does solve the specific case up to 8 bytes.
I was thinking more to have a catch all phrase in the case statement which catches all abnormal cases:
` _ -> {Error,description}`

But your solution works for the current issue we had, so if the catch all phrase is too hard to implement, I'm OK with the current fix.

Thanks for the quick solution.

**Comment by nakagami** [comment]
Tnanks !

0.9.9 is released on hex.pm
https://hex.pm/packages/efirebirdsql/0.9.9

Please use it
