### ISSUE TITLE
select nullable column error

### ISSUE THREAD

**Issue by abeniaminov** [nakagami/efirebirdsql#3]
Dear Hajime!

It seems to me that is's problem with select null valued column. 

(prime@udeis)1>   {ok, C} = efirebirdsql:connect( "localhost", "sysdba", "masterkey", "employee", []).
{ok,<0.41.0>}

(prime@udeis)2> ok = efirebirdsql:execute(C, <<"select EMP_NO, FIRST_NAME from employee where EMP_NO = 2">>).
ok
(prime@udeis)3> {ok, Result1} = efirebirdsql:fetchall(C).
{ok,[[{<<"EMP_NO">>,2},{<<"FIRST_NAME">>,<<"Robert">>}]]}

(prime@udeis)4> ok = efirebirdsql:execute(C, <<"select EMP_NO, FIRST_NAME from employee where EMP_NO = 72">>).
ok
(prime@udeis)5> {ok, Result2} = efirebirdsql:fetchall(C).  
{ok,[[{<<"EMP_NO">>,72},{<<"FIRST_NAME">>,<<"Claudia">>}]]}

(prime@udeis)6> ok = efirebirdsql:execute(C, <<"select EMP_NO, FIRST_NAME, PHONE_EXT from employee where EMP_NO = 2">>). 
ok

(prime@udeis)7> {ok, Result3} = efirebirdsql:fetchall(C).  
{ok,[[{<<"EMP_NO">>,2},
      {<<"FIRST_NAME">>,<<"Robert">>},
      {<<"PHONE_EXT">>,<<"250">>}]]}

(prime@udeis)8> ok = efirebirdsql:execute(C, <<"select EMP_NO, FIRST_NAME, PHONE_EXT from employee where EMP_NO = 72">>).

after that all hang up. I know exactly that PHONE_EXT is null when EMP_NO = 72

**Comment by nakagami** [comment]
I think fixed in master branch. Please pull and check it.

**Comment by abeniaminov** [comment]
It's ok.
