### ISSUE TITLE
return blob value

### ISSUE THREAD

**Issue by abeniaminov** [nakagami/efirebirdsql#4]
Dear Hajime,

efirebirdsql_op.erl lines 476 - 477 generate error when length of SegmentList  > 1

[R] = lists:flatten(SegmentList),
 {ok, R}.

It would be  

R = list_to_binary(SegmentList),
{ok, R}

?

**Comment by nakagami** [comment]
Thanks, you are right.

1> SegmentList = [<<"Seg1">>, <<"Seg2">>].
[<<"Seg1">>,<<"Seg2">>]
2> list_to_binary(SegmentList).
<<"Seg1Seg2">>
3> lists:flatten(SegmentList).
[<<"Seg1">>,<<"Seg2">>]
4> 

I will fix it, soon.
