### ISSUE TITLE
Handling {:error,:closed} on dropped connection

### ISSUE THREAD

**Issue by hermanius** [nakagami/efirebirdsql#7]
Hi,

thanks for creating the efirebird app, I like it a lot. 

I'm using efirebirdsql (0.8.1) connections in Elixir/Phoenix inside a Poolboy worker (GenServer) for performance reasons.
When a connection to the Firebirdsql server drops, for example because of a network connection failure, and I do for example a :firebird.execute on that connection, the firebird genserver crashes (and restarts) because of:
** (MatchError) no match of right hand side value: {:error, :closed}
    (efirebirdsql 0.8.1) <myapp>/deps/efirebirdsql/src/efirebirdsql_op.erl:482: :efirebirdsql_op.get_response/1

Looking into the source code it, I can see indeed, only the ok atom is handled:
{ok, <<OpCode:32>>} = efirebirdsql_socket:recv(Conn, 4),

Would you consider enhancing efirebirdsql so errors in this call are also returned in stead of crashing the genserver? It would allow me to handle these errors more elegantly towards users of the website.

**Comment by nakagami** [comment]
I don't know how to fix it, but I'd like to fix it if possible, so someone please send me a pull request.

**Comment by nakagami** [comment]
Or is it better to leave it crashing?
Can't we just detect a crash and reconnnect?

**Comment by hermanius** [comment]
I see your point in letting it crash, which is of course also a bit the philosophy of Erlang/Elixir.
Looking a bit more into the source code you rely on it in a lot of places where only the ok atom is handled. I suppose it would be a fairly big task to handle the error condition in all these places.
I will first look into handling the crashes in the Poolboy workers. If that does not work out I will consider creating a pull request although I'm more used to Elixir than Erlang.
Thanks for your reaction already.

**Comment by nakagami** [comment]
It may be that there is a connection timeout in the socket.
If so, and if extending the timeout time would work, perhaps a timeout argument to efirebirdsql:connect() would help.

I hope someone will try it and send me a pull request!

**Comment by hermanius** [comment]
I don't know wether I understand your suggestion correctly. The crash of the efirebird genserver I'm experiencing is not because of a timeout when connecting, but because of, for example, a network failure after a connection was already established (connections in poolboy are long lived).
As you suggested, I have solved the issue by handling efirebirdsql crashes in the poolboy workers, and reconnecting after a crash. So for me, this is a good solution, and I'm very much OK with closing the issue.
Thanks for all the help.

**Comment by nakagami** [comment]
I don't know poolboy, but I see you have a solution.
If so, this issue is closed.
