### ISSUE TITLE
insert nil in BLOB SUB_TYPE BINARY hangs

### ISSUE THREAD

**Issue by hermanius** [nakagami/efirebirdsql#8]
Hi,

I have a table with a field that is of type BLOB SUB_TYPE BINARY (NULL allowed).
When I execute an insert statement through efirebirdsql with a nil value for this field, efirebirdsql just hangs.
e.g. in Elixir code:  :efirebirdsql.execute(conn,"INSERT INTO table (field1,blobfield2) values (?,?)",["foo",nil])

Should I pass something else than nil as a parameter?

**Comment by nakagami** [comment]
Umm, something's wrong.
I haven't been able to fix it yet. (I may have gotten a little closer, but I'm not sure.)
Please wait a while.

**Comment by nakagami** [comment]
0.8.2 has been released
Please check if it works properly.

**Comment by hermanius** [comment]
0.8.2 Solves the issue for my use case. Awesome!!
Thank you very much sir.
